version: "3.8"
services:

  server:
    build: ./server
    ports:
      - '80:80'
    volumes: 
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    ports: 
      - '1234:1234'
    volumes: 
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - server
    deploy:
      resources:
        limits:
          memory: 1g  

volumes: 
  data:

